org: svengerlach
app: workout-tracker-api
service: workout-tracker-api

provider:
  name: aws
  runtime: nodejs16.x
  deploymentMethod: direct
  region: us-east-1
  stage: ${opt:stage, self:custom.defaultStage}

custom:
  defaultStage: ${env:DOPPLER_ENVIRONMENT}

functions:
  api:
    handler: serverless.handler
    environment:
      CLIENT_ORIGIN: ${env:CLIENT_ORIGIN}
      MONGO_URI: ${env:MONGO_URI}
    events:
      - http:
          method: ANY
          path: /
          cors: true
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true

plugins:
  - serverless-offline
